id: P010636
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:17:33.196770
source_metadata:
  id: bdr:W27476
  title: རྒྱ་བོད་ཧོར་སོག་གི་མཆོག་དམན་བར་པ་རྣམས་ལ་འཕྲིན་ཡིག་སྙན་ངག་ཏུ་བཀོད་པ་རབ་སྙན་རྒྱུད་མང
  author: ''
  volumes:
    abb158cf1b72479581efd78a0d128324:
      image_group_id: I4356
      title: ''
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
