id: P010636
initial_creation_type: ocr
source_metadata:
  id: bdr:W27476
  title: རྒྱ་བོད་ཧོར་སོག་གི་མཆོག་དམན་བར་པ་རྣམས་ལ་འཕྲིན་ཡིག་སྙན་ངག་ཏུ་བཀོད་པ་རབ་སྙན་རྒྱུད་མང
  author: ''
  volumes:
    abb158cf1b72479581efd78a0d128324:
      image_group_id: I4356
      title: ''
      volume_number: 1
      total_pages: 586
