id: I1A875851
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:01:25+00:00'
last_modified: '2022-06-08T16:24:45.331789+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27476
  title: རྒྱ་བོད་ཧོར་སོག་གི་མཆོག་དམན་བར་པ་རྣམས་ལ་འཕྲིན་ཡིག་སྙན་ངག་ཏུ་བཀོད་པ་རབ་སྙན་རྒྱུད་མང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A471:
      image_group_id: I4356
      title: ''
      total_pages: 586
      order: 1
      base_file: A471.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
