id: I1A875851
legacy_id: P010636
ocr_import_info:
  bdrc_scan_id: W27476
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T16:58:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:17:22.821089+00:00'
last_modified: 2022-09-02 15:18:04.180500
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27476
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27476
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱ་བོད་ཧོར་སོག་གི་མཆོག་དམན་བར་པ་རྣམས་ལ་འཕྲིན་ཡིག་སྙན་ངག་ཏུ་བཀོད་པ་རབ་སྙན་རྒྱུད་མང་།
  author: ཏཱ་ལའི་བླ་མ ༠༥་ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6713384526067735
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I4356:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4356
      total_pages: 586
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4356.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6713384526067735
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
